title: GitHub_DevOps
tagline: A brand new course on Learning Lab
description: This is an introction to GitHub DevOps
template:
  repo: github_devops-template
  name: github_devops-created
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    video: https://youtube.com/embed/w3jLJU7DT5E
    event: issues.assigned
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: closeIssue
  - title: Second step
    description: The 2nd step in your course
    event: issues.assigned
    link: 'https://youtube.com/embed/w3jLJU7DT5E'
    actions:
      - type: closeIssue
